#+title: Python instead of jq
#+description: How to use Python instead of jq
#+keywords: Python,jq,JSON
#+options: smartquotes:nil
#+options: html-style:nil html-scripts:nil author:nil validate:nil html-allow-html:t tex:t ':nil ...:nil -:nil
#+tags: Python,jq,JSON
#+date: <2026-07-22 Wed 20:32>

* jq

To query JSON file like XML with XPath or XQuery, you can use a command line tool called
[[https://jqlang.org/][jq]]. It's great but you can use Python also.

* Python querying JSON

You can load JSON file very easy:

#+begin_src python :eval no :exports both
import json
with open(path_to_json_file, 'rt') as f:
    json_data = json.load(f)
#+end_src

but more interesting is that you can query JSON as some DB. Considering our decoded JSON
in this way:

#+begin_src python :session *Python_instead_of_jq* :eval yes-export :exports both :results output verbatim
dat = {
    'project': {
        'name': 'Demo',
        'config': {
            'databases': [
                {
                    'name': 'DB1',
                    'primary': {
                        'host': '10.0.0.5',
                        'port': 5430
                    },
                    'replicas': [
                        {
                            'host': '10.0.0.5',
                            'port': 5431
                        },
                        {
                            'host': '10.0.0.5',
                            'port': 5437
                        }
                    ]
                },
                {
                    'name': 'DB2',
                    'primary': {
                        'host': '10.0.0.12',
                        'port': 5433
                    },
                    'replicas': [
                        {
                            'host': '10.0.0.15',
                            'port': 5434
                        }
                    ]
                },
                {
                    'name': 'DB3',
                    'primary': {
                        'host': '10.0.0.5',
                        'port': 5437
                    }
                }                
            ]
        }
    }
}
#+end_src

#+RESULTS:

and let's try some queries:

#+begin_src python :session *Python_instead_of_jq* :eval yes-export :exports both :results output verbatim
databases = dat.get('project',{}).get('config',{}).get('databases',[])
q = len(databases)
print(f'NUMBER OF DATABASES: {q}')

q = {d.get('name', 'Unnamed') for d in databases}
print(f'DATABASES: {q}')

q = {d.get('primary', {}).get('port') for d in databases} \
  | {r.get('port') for d in databases for r in d.get('replicas',[])}
print(f'PORTS IN USE (WAY 1): {q}')

q = { *(d.get('primary', {}).get('port') for d in databases),
      *(r.get('port') for d in databases for r in d.get('replicas',[])) }
print(f'PORTS IN USE (WAY 2): {q}')

q = set( [d.get('primary', {}).get('port') for d in databases] +
         [r.get('port') for d in databases for r in d.get('replicas',[])])
print(f'PORTS IN USE (WAY 3): {q}')

q = { (d.get('name', 'Unnamed'), p) for d in databases
      if (p:=d.get('primary', {}).get('port')) and p > 5430 }
print(f'DATABASE NAMES WITH PORTS WHERE PRIMARY PORT > 5430: {q}')
#+end_src

#+RESULTS:
: NUMBER OF DATABASES: 3
: DATABASES: {'DB2', 'DB1', 'DB3'}
: PORTS IN USE (WAY 1): {5430, 5431, 5433, 5434, 5437}
: PORTS IN USE (WAY 2): {5430, 5431, 5433, 5434, 5437}
: PORTS IN USE (WAY 3): {5430, 5431, 5433, 5434, 5437}
: DATABASE NAMES WITH PORTS WHERE PRIMARY PORT > 5430: {('DB3', 5437), ('DB2', 5433)}

You see idea - we can use list/set/dict comprehension and ~dict.get(KEY, DEFAULT)~ method (as
well as different tricks). Let's do something more complex - to query conflicting ports if they
exist - they should be on the same host:

#+begin_src python :session *Python_instead_of_jq* :eval yes-export :exports both :results output verbatim
from collections import defaultdict

dd = defaultdict(set)

for k, v in (
    [((ph, pp), d.get('name', f'Unnamed{i}'))
     for i, d in enumerate(databases)
     if (prim := d.get('primary', {}))
     and (ph := prim.get('host'))
     and (pp := prim.get('port'))]
    +
    [((rh, rp), d.get('name', f'Unnamed{i}'))
     for i, d in enumerate(databases)
     for repl in d.get('replicas', [])
     if (rh := repl.get('host'))
     and (rp := repl.get('port'))]
): dd[k].add(v)
conflicts = {k:v for k,v in dd.items() if len(v) > 1}
print(f'DATABASES HAVING PORT CONFLICTS (WAY 1): {conflicts}')
#+end_src

#+RESULTS:
: DATABASES HAVING PORT CONFLICTS: {('10.0.0.5', 5437): {'DB1', 'DB3'}}

But this is not so good query: we pass through ~databases~ 2 times. Lets try to rewrite it:

#+begin_src python :session *Python_instead_of_jq* :eval yes-export :exports both :results output verbatim
import pprint
dd = defaultdict(set)
q = [dd[rec[:2]].add(rec[2])
     for db in [[(ph, pp, name), (rh, rp, name)]
                for i, d in enumerate(databases)
                for name in [d.get('name', f'Unnamed{i}')]
                for prim in [d.get('primary', {})]
                for ph in [prim.get('host')]
                for pp in [prim.get('port')]
                for repl in d.get('replicas', [{}])
                for rh in [repl.get('host')]
                for rp in [repl.get('port')]]
     for rec in db if rec[0] and rec[1]]
conflicts = {k:v for k,v in dd.items() if len(v) > 1}
print(f'DATABASES HAVING PORT CONFLICTS (WAY 2): {conflicts}')
#+end_src

#+RESULTS:
: DATABASES HAVING PORT CONFLICTS (WAY 2): {('10.0.0.5', 5437): {'DB1', 'DB3'}}

As you can see it looks mostly as Haskell's ~do-notation~ for list monad - [[https://www.schoolofhaskell.com/school/starting-with-haskell/basics-of-haskell/13-the-list-monad][example]]!

Though, it is not optimal: it iterates over ~databases~ only once, but it recreates the same
tuples. This can be fixed but only partially - with ~for t1 in [(ph,pp,name)]~. If you need
performance then you should switch to block-wise code:

#+begin_src python :eval no :exports both
for db in databases:
    t1 = ...
    ...
    for repl in db['replicas']:
        t2 = ...
        ...
#+end_src


# TODO

* Other options

Other options could be... C# [[https://learn.microsoft.com/en-us/dotnet/csharp/linq/][LINQ]] or Groovy's [[https://groovy-lang.org/using-ginq.html][GINQ]]
