#+title: Using Why3 for software verification
#+description: Introduction to Why3 for software verification
#+keywords: why3,whyml,theorem,proving
#+options: smartquotes:nil
#+options: html-style:nil html-scripts:nil author:nil validate:nil html-allow-html:t tex:t ':nil ...:nil -:nil
#+property: header-args :eval no-export
#+tags: Why3 WhyML Theorem Proving
#+date: <2026-09-25 Fri 07:50>

* The idea

Very briefly, because today everyone knows what it is. The idea is that in mathematics, logic,
you prove theorems but the idea is that it can be done "automatically", well, not absolutely
automatically but using a computer: see [[https://en.wikipedia.org/wiki/Automated_theorem_proving][Automated theorem proving]]. And this allows to
mathematicians to state proving more formal, and more strict, "provable". But it is for math.

The idea is that the same approach can be used for proving of some properties of software.

* Why it matters in the epoch of AI

People see that theorem provers become more and more popular. Why?

1. They become more mature and better
2. The cost of "error" becomes big (hackers, buggy code, etc)
3. Their number is increasing
4. "Buzz-word"
5. AI effect

What is "AI effect"? There is now a fairly substantial ecosystem where an AI proposes a
mathematical statement/proof, and a theorem prover such as Lean acts as the trusted
checker. There are also projects where the prover catches errors in the AI-generated/formalized
result itself. Examples (however, more close is ProofNet-Verifided):

- [[https://github.com/marcusm117/ProofNet-Verified][ProofNet-Verified]]: a benchmark where natural-language undergraduate mathematics
  is translated into Lean
- [[https://leandojo.org/leandojo][LeanDojo]] / [[https://github.com/lean-dojo/ReProver][ReProver]]: LLM proposes proofs, Lean verifies them
- [[https://github.com/Kripner/openprover][OpenProver]]: workers generate mathematical ideas/proof steps, while verification is delegated
  to Lean
- [[https://github.com/facebookresearch/miniF2F][MiniF2F]]: math problem is proved by LLM then LEAN check it
- [[https://paperswithlean.com/paper/2606.20068.html][Process-Verified RL]]: a newer direction, instead of merely asking: "Did the AI eventually
  produce a correct proof?" the researchers use Lean to provide fine-grained feedback during
  the proof process. LLM generates several steps, LEAN reject some of them

So, the collaboration between theorem provers and AI/LLM today looks as:

| Use                               | AI does                                    | Theorem prover does                                             |
|-----------------------------------+--------------------------------------------+-----------------------------------------------------------------|
| Proof generation                  | Invents a proof                            | Checks it                                                       |
| Proof correction                  | Proposes another proof after failure       | Identifies invalid steps                                        |
| Result/formalization verification | Translates a human result into formal math | Determines whether the formal statement/proof is actually valid |

So, one of the scenario is:

#+begin_example
             Human/AI
                 |
                 v
       Natural-language result
                 |
                 v
       .------------------.
       |   LLM / Agent     ‖
       | autoformalization ‖
       `====================
                |
                v
  Lean, Isabelle, Rocq, Metamath
                |
        .-------+--------.
        |                |
      VALID           INVALID
        |                |
        v                v
   accept result    feedback to AI
                         |
                         `--> revise
#+end_example

* Why Why3

[[https://why3.org/][Why3]] is such a tool: you describe your "model" (of a program) then its properties then you
prove them. If successfully then your software (different pieces of your code) is safe (as you
described "safety" with those properties), else - you think about your code something, but it
is something else.

#+begin_quote
Why3 is a platform for deductive program verification. It provides a rich language for
specification and programming, called WhyML, and relies on external theorem provers, both
automated and interactive, to discharge verification conditions.

-- https://why3.org/
#+end_quote

** Why3 features

TODO  WhyDo etc

* Other tools

There are a lot of automatic (computer) provers, their features are different, they work in
different ways, some of them are:

1. for mathematics
2. for mathematics and computer science (including software)

My focus is 2nd:

- [[https://why3.org/][Why3/WhyML]]
- [[https://dafny.org/][Dafny]]
- [[https://fstar-lang.org/][F*]]
- [[https://rocq-prover.org/][Rocq]] (former Coq)
- [[https://lean-lang.org][LEAN]]
- etc...

* Comparison of tools for computer science

TODO

* How much does this save you from bugs?

After proof, your code may still contain errors. This is due to:

- you did not enumerate all important properties, you missed something
- there are "not logical" bugs, for example, error (additive, for example) is too large, ie,
  the software is not accurate enough in numerical calculation
- bugs happen outside of verified code - in the effectful world (API, network, libraries, OS...)
- serious performance problems
- policy related errors: bad UX, strange behavior on errors, weird understanding of the domain
  problems...
- bad design
- sometimes even proof can be not good enough (the probability of this is low: automatic
  verification checks the correctness of the proof)

After proof usually you get:

- More correct code (or even significantly more correct, sometimes - code without bugs at all)
- You better understand your code and its corner cases, features, its pros and cons

* Setup of Why3 on Linux

Why3 can be installed from your distribution package manager. Also it comes with its default
SMT solvers. Currently, it is CVC4, but it is not so good, and you can hit problems with
it. So, I'd recommend to install Z3 SMT solver from the package manager and then to configure
Why3 to "see" it:

#+begin_example
$ why3 config detect
$ why3 config list-provers   # and you should see Z3 now in the list
# After it use can use z3 during prooving woth "-P z3" option
#+end_example

* Why proving is "metaprogramming"

There is such a term - [[https://en.wikipedia.org/wiki/Metaprogramming][metaprogramming]] and logic "lives between liens of code" or on the top of
it, not participating in computation but checking/verifying it: *it is a program about program*.

* Extraction

Why3 supports extraction too, see [[https://why3.org/doc/manpages.html#the-extract-command][this]] and [[https://why3.org/doc/exec.html#sec-extract][this]]. It can translate (correct term is EXTRACT
though) your WhyML program to Ocaml, Java, C, CakeML.

* Usage scenarios

Main are:

- proving of existing code
- proving of idea, algorithm including distributed one ([[https://github.com/haslab/why3do/tree/main/examples/paxos][PAXOS verified with WhyML]])
- extracting of verified code to be used in an existing project

* Program and logic: computational and logic code

All WhyML code is split to 2 pies - WORLDS: a program (computational) "world" and logic
"world". And... there are constructions living in both "worlds".

- *Program/computational WhyML code* — code that describes computation: functions, mutable
  state, references, loops, exceptions, I/O, etc. It is executed or compiled.
- *Logical code* — specifications and mathematical objects used to reason about the program:
  predicates, propositions, lemmas, axioms, pure functions, mathematical types, etc. It is not
  executed as program code; it is translated into proof obligations for automated/theorem
  provers.

So, logical world (code) is metaprogramming. Computational (or program) world (code) is your
program. Also it matters in extraction phase - logical code will not generate Ocaml, C output,
in short.

* Solver, SMT, SAT...

About SMT and SAT in [[https://en.wikipedia.org/wiki/Satisfiability_modulo_theories][Wikipedia]].

** SAT

SAT solves boolean "satisfiability" answering the question: "Can I assign true/false to these
boolean variables so that the whole formula becomes true?", example:

#+begin_example
Input formula :            (A OR B) AND (NOT A OR C)

A SAT solver might find :  A = false
                           B = true
                           C = false

                           
#+end_example

It's kind of utility helper in the world of automatic logic. SAT works fundamentally with
~true/false~, ~AND, OR, NOT~... It is something like "constraint programming over boolean
domain".

#+begin_quote
A SAT solver doesn't inherently understand things like:

x + 1 > x

because ~x~ there isn't a boolean variable.
#+end_quote

** SMT

SMT means "Satisfiability Modulo Theories", it answers the question: "Is there an assignment
that makes this formula true?", but SMT allows variables from particular mathematical theories.

For example, integer arithmetic:

#+begin_example
Input :                   x: Int
                          y: Int
                          x > 10
                          y = x + 5
                          y < 20

                          
SMT solver might find :   x = 11
                          y = 16
#+end_example

SMT works in domains:

- integers and real numbers
- arithmetic
- arrays
- bit-vectors
- equality
- uninterpreted functions
- sometimes strings (CVC 4 (strings), etc), floating point, etc.

Modern SMT solvers combine: Boolean reasoning of SAT with its own standard Theory reasoning,
i.e., SAT today is usually embedded part of SMT.

Why3, Dafny, F*, etc, delegate "simple" work to SMT. Rocq, LEAN - do not (they can do all work
by self, but they allow to use external solvers).

** How Why3 communicate with SMT

#+begin_example
                .---------------------.
                |       WhyML         ‖
                |  program + specs    ‖
                `======================
                           |
             verification  |              
                           v
                .---------------------.
                |   Why3 VC Generator ‖
                |       (VCgen)       ‖
                `======================
                           |
                      Verification
                    Conditions (VCs)
                           |
                           v
                .---------------------.
                |   Why3 Transform    ‖
                |                     ‖
                | simplify / split /  ‖
                | instantiate / etc.  ‖
                `======================
                           |
                SMT-LIB    |         
               .-----------+-----------.
               |           |           |
               v           v           v
            .-----.     .-----.     .------.
  SMT       | Z3  ‖     |CVC5 ‖     | Alt- ‖
solvers     |     ‖     |     ‖     | Ergo ‖
            `======     `======     `=======
               |           |           |
               `-----------+-----------'
                           |
                       SAT, UNSAT
                           |
                           v
                .---------------------.
                |        Why3         ‖
                |    proof result     ‖
                `======================
#+end_example

The "route" of the input WhyML program;

#+begin_example
.----------[ WhyML ]-----------.
|  let f (x: int) : int        ‖    Your WhyML code
|   ensures { result >= x } =  ‖   
|  x + 1                       ‖   
`===============================   
               |                   Why3 generates VC
               v                   (verification condition)
 .----------[ VC ]-------------.   
 |     ∀ x:int. x + 1 >= x     ‖   
 `==============================   Why3 translates it to the language
               |                   understood by the selected prover
               v                   (typically SMT-LIB)
.---------[ Z3 QUERY ]----------.  
| (declare-const x Int)         ‖  
| (assert (not (>= (+ x 1) x))) ‖  
| (check-sat)                   ‖  
`================================   Why3 gets output from SMT solver...
#+end_example

Why3 *is not a frontend to a SMT solver* - Why3 has its own intermediate logical language and
transformation system. It can manipulate a proof goal before handing it to an automated prover:

#+begin_example
             WhyML
               |
               v
         .------------.   ....
         |   VCgen    ‖       ⋱
         `=============        :
              VC               :
               |               :
               v               :
         .------------.         ⋱  Why3
         | Transform  ‖         ⋰  work
         |            ‖        :
         | split_goal ‖        :
         | simplify   ‖        :
         | induction  ‖        :
         | specialize ‖        :
         `=============   ....⋰
               |
      .--------+--------.
      v                 v
  SMT solver       Interactive
  (Z3/CVC5/...)      prover
#+end_example

Also Why3 can combine provers:

#+begin_example
         :
        VC
         |
    .----+----.
    v         v
   Z3      Alt-Ergo
    |         |
    `----+----'
         |
         v
       proved
#+end_example

Also Why3 records the resulting proof information so that the verification can be
checked/replayed later.

* Example

Before, I wrote this ([[./Packs_Search.org][Packs Search]]) simple algorithm. It was written with memory exploitation
which allows to visualize the algorithm's phases, steps - it could be written in other ways too
but this way is more "visual". Visualization also is kind of "proving" of an algorithm, but it
is not real logic-based proof. Let's fill this gap with Why3.

I posted the WhyML proof code [[https://github.com/disco85/packs_verification/blob/main/Packs.mlw][here]]. Let's walk through some fragments of the current state of
the code and comments them.

** Fragment 1

#+begin_example
1   type num =
2     | NaN
3     | MinusInf
4     | Fin int
5     | PlusInf
#+end_example

Here we declare [[https://en.wikipedia.org/wiki/Algebraic_data_type][ADT]] which models Not-a-Number, Minus Infinity, Finite integer (usual), Plus
Infinity. We use it later, in the original Python code I used float numbers and Python support
these special values internally.

** Fragment 2

#+begin_example
 1   let calc_diffs (ps: array int) (absolute: bool) : array int =
 2   ensures {
 3     (length ps = 0 -> length result = 0) /\
 4     (length ps > 0 -> length result = length ps - 1)
 5   }
 6     let diffs_num = max ((length ps) - 1) 0 in
 7     let diffs = make diffs_num 0 in
 8     let i:ref int = ref 0 in
 9     if diffs_num = 0 then
10       diffs
11     else begin
12       while !i <> length ps - 1 do
13       invariant { 0 <= !i <= length ps - 1 }
14       invariant { !i <= length diffs }
15       variant { length ps - 1 - !i }
16         let diff = ps[!i + 1] - ps[!i] in
17         let diff = if absolute then abs diff else diff in
18         diffs[!i] <- diff;
19         incr i
20       done;
21       diffs
22     end
#+end_example

First, we see on ~1~ the declaration of the function ~calc_diffs~ which has 2 arguments: an
array of integers and a boolean, and it returns an array of integers. Also it has one
postcondition on line ~2~ (see ~ensures {..}~), it could have preconditions too...

postcondition on ~2~ says: there are 2 statements - they are formed as ~first AND second~
("and" is ~/\~):

1. ~(length ps = 0 -> length result = 0)~
   If the length of the argument ~ps~ is 0 then the result of the function will have a length 0 too
2. ~(length ps > 0 -> length result = length ps - 1)~
   If the argument ~ps~ is not empty then the length of the result is lesser of ~ps~ by 1.

Why3 will check the code of the function and will prove or refute such statements, you can do
it by self:

1. initially the loop variable ~i~ is 0
2. it's bound is ~length ps - 1~ (on ~12~)

Why3 does it automatically, for you.

*These properties (postconditions in the case) are important: you know what to expect from the
function.*

Also they will be used in proving of other pieces of the code, they are "a contract", and when
it is called somewhere, Why3 can reason about its result.

Types matter - they are also controlled by Why3 - if an expression violates the declared type,
it is also reported as an error, obviously.

Inside ~while~ loop we see ~invariant~ and ~variant~ expressions. "Invariant" describes
something that does not change - it is checked too also this knowledge is remembered as a fact
and can be used later for further proving. These 2 invariant expressions do state:

- ~invariant { 0 <= !i <= length ps - 1 }~
  we guarantee inside the loop that ~i~ is always in this diapason, i.e., ~[0..length ps-1]~
- ~invariant { !i <= length diffs }~
  also we guarantee that ~i~ is always lesser or equal to the length of the array ~diffs~

Little note: ~!~ in the front of ~i~ is "dereferencing" like "*" in C - "take the content of
the reference" - to be mutable we declared ~i~ as reference.

OK, also we see "variant". The idea of a variant expression is more interesting: it guarantees
that something is "decreasing" - it states "what" does it. Why do we need it? Usually it is
needed in:

- ~while~-loop (in ~for~-loop it is obvious, so it is redundant and syntactically denied)
- in recursive functions

"Variants" state that something becomes smaller and smaller and this thing is known as
something having "ZERO" - the smallest form, it cannot become "smaller" and it guarantees Why3
that looping construction will complete (it is not forever-running, it will terminate) - most
looping constructions are such ones. Sure, exceptions of this are supported (~diverges~
keyword). OK, so here: ~variant { length ps - 1 - !i }~ we say that this "thing" (expression)
becomes smaller and smaller, considering the length of ~ps~ is 3:

| !i | 3 - 1 - !i (ie, length ps - 1 - !i) | treating                    |
|----+-------------------------------------+-----------------------------|
|  0 |                                   2 | search further...           |
|  1 |                                   1 | search further...           |
|  2 |                                   0 | 0 = SMALLEST, STOP IS HERE! |

Theorem provers know: if we hit the smallest "thing" (and it checks the code sure, that it's
true), then we reach the end of the looping. It means - no infinite loop here.

*Variant expression just focus Why3 what "thing" to check for termination - the decrease of it
is checked by Why3 itself*

Such "things" can be integers, lists (reaching of ~Nil~ - the empty tail), etc.

And *these "variants" and "invariants" give knowledge about looping constructions: what is true
on every step/iteration, what does guarantee that the end of the loop or recursion.*

Let's continue.

** Fragment 3

#+begin_example
 1   let rec list_min (l: L.list int) : int =
 2   requires { l <> L.Nil }
 3   variant  { LL.length l }
 4     match l with
 5     | L.Nil -> absurd
 6     | L.Cons x L.Nil -> x
 7     | L.Cons x r ->
 8         let m = list_min r in
 9         if x < m then x else m
10     end
#+end_example

New here is that it consumes list, not array. Also it is a "program" (i.e, computational)
function (due to ~let~ keyword!). And it is recursive (~rec~ keyword). It has ~requires~
expression which says that ~list_min~ is allowed to be called only with a non-empty list: Why3
will check all places where it is called. Also it is a contract meaning: a function will
guarantee (see ~ensures~) if its requirements will be satisfied.

And you see ~variant~ again focusing Why3 what should be checked for termination - it is the
length of the list ~l~, also we can write directly ~variant { l }~ - it is the same. It is our
termination measure, because we call ~list_min~ recursively passing it the tail of the list
~l~, which means that on every call ~l~ becomes smaller and smaller (we "chop" the list). Can
we violate the requirement? No, because we stop on line ~6~ and return ~x~ without to dive
deeper in a recursive call. Also we have pattern matching on ~l~ and it should have a branch
for empty list - it is line ~5~. What do we do there? We use ~absurd~ which means in the
context of computational/program code - "check if it is really absurd code and it can never
happen". Why3 will check it (in computational context). *If it is not - it will be reported as
an error!*

** Fragment 4

This is helper-function, needed mostly in logic (so, I could make it ghost, I think):

#+begin_example
  let rec function list_nth (l: L.list int) (n: int): option int =
  requires { 0 <= n < LL.length l }
  ensures {
    match result with
    | Some el -> LM.mem el l
    | None    -> false
    end
  }
  variant { n }
  match l with
  | L.Cons x tl -> if n = 0 then Some x else list_nth tl (n - 1)
  | L.Nil -> None
  end
#+end_example

How to read it: input argument ~n~ must be in this range being passed to the function (it
reminds [[https://en.wikipedia.org/wiki/Refinement_type][refinement types]]) and cos it's a recursive function - it have a "measure of
termination", i.e., ~variant~ expression in its contract: we recursively call ourselves (~rec~)
with decreasing of ~n~. More interesting is ~ensures~ part of the contract: it guarantees that
the result exists if it is a member (see ~mem~) of the list ~l~. It sounds strange, but I used
it to expose out the connection between "nth item" and "it is an item of list". It sounds
strange but provers often need facts obvious to you but not for them.

** Fragment 5

I checked Python program where lists have some duality: they are easy accessible by an index
but at the same time they are like usual lists: you can append items to them, etc. So, I used
arrays and lists in my WhyML - and I feel that it is not the best solution :)

Anyway, so, I needed a way to convert list to array. This helper function does it. It ensures
not only preserving of the length but also that the same elements are on the same positions -
see the second ~ensures~ on line ~3~:

#+begin_example
 1  let list_to_array (l: L.list int) : array int =
 2    ensures { LL.length l = length result }
 3    ensures {
 4      (* preserving of elements *)
 5      forall k:int. 0 <= k < LL.length l ->
 6        Some result[k] = list_nth l k
 7    }
 8    let a = make (LL.length l) 0 in
 9    for i = 0 to LL.length l - 1 do
10      invariant { 0 <= i <= LL.length l }
11      invariant {
12        forall k:int. 0 <= k < i ->
13          Some a[k] = list_nth l k      (* check of history *)
14      }
15      match list_nth l i with
16      | Some el -> a[i] <- el;
17      | None    -> absurd
18      end;
19    done;
20    a
#+end_example

Invariants are needed to say: "At every loop iteration, the current state must satisfy this
formula, and this formula summarizes the relevant consequences of all previous iterations.", it
is like setting of the induction hypothesis like:

#+begin_example
∀ k < i →
    a[k] = l[k]
#+end_example

roughly, we can use why3 command's option =--print-theory=:

#+begin_example
   ...
 1   (forall a1:array int.
 2     a1.length = a.length ->
 3     (forall i:int.                   ⋱... our  for i = 0 to LL.length l - 1
 4       (0 <= i /\ i <= o2) /\         ⋰
 5       (0 <= i /\ i <= length1 l) /\                                    ⋱... invariants
 6       (forall k:int. 0 <= k /\ k < i -> Some a1[k] = list_nth l k) ->  ⋰
 7       (0 <= i /\ i < length1 l) /\
 8       (let o3 = list_nth l i in
 9        match o3 with
10        | Some el -> mem el l
11        | None -> false
12        end ->
   ...
22           (0 <= (i + 1) /\ (i + 1) <= length1 l) &&
23        (forall k:int.
24          0 <= k /\ k < (i + 1) -> Some a2[k] = list_nth l k))
   ...
#+end_example

Something like:

#+begin_example
    Assume invariant(i)
            |
            v
    execute iteration
            |
            v
  prove invariant(i+1)
#+end_example

This converts an unbounded history problem into a finite induction proof: "Every iteration I've
performed so far correctly copied its element." It reminds the usual induction:

#+begin_example
Base:
    I(S₀, 0)

Step:
    I(Sᵢ, i) ∧ transition(Sᵢ, Sᵢ₊₁)
       ⇒ I(Sᵢ₊₁, i+1)

Exit:
    I(Sₙ, n) ∧ exit-condition
       ⇒ postcondition
#+end_example

/where S is for "a state"/.

** Fragment 6

Another helper ghost (see ~predicate~) code:

#+begin_example
1   predicate list_elems_are_correct_index (l: L.list int) (n: int) =
2   (* The predicate checks that all elements in the list `l` can be index bounded by `n`,
3    * ie, 0 <= el < n. It is used in `list_elems_are_correct_index__append_singleton` lemma
4    *)
5     match l with
6     | L.Nil      -> true
7     | L.Cons x r -> 0 <= x < n /\ list_elems_are_correct_index r n
8     end
#+end_example

It checks that all items in a list can be indexes of some sized object which size is ~n~, i.e.,
they are bound by ~[0..n)~.

#+begin_example
 1   (* This lemma is needed to prove the invariant:
 2    *
 3    *   invariant { list_elems_are_correct_index !res_ranges (length res_ps_arr) }
 4    *
 5    * in `approximate_by_rectangles`. This invariant tells that every item is `res_ranges`
 6    * is a index of items in `res_ps`/`res_ps_arr` (`res_ranges` is a list of indexes, so
 7    * no one item in `res_ranges` can violate the `res_ps` bounds - it can be useful in
 8    * the next function: `find_clusters_centers`). But to prove this invarint, we have
 9    * to hint Why3 with some lemma. Without it, we hit timeout/out of memory.
10    *
11    * It seems the timeout problem is connected with construction of a list and need to
12    * check the invariant when the list is growing (?) - we add `i` to the list, and we
13    * know that `i` is inside bounds, so Why3 has to check that adding only of `i` to a
14    * list means that all items of that list are inside the same bounds. More detailed:
15    * Z3/CVC4/... do not automatically know that `list_elems_lt` is preserved by `++` !
16    *
17    * This lemma proves it by induction. `requires` is A, `ensures` is B in A -> B.
18    * `variant` is a termination measure (bcs the lemma is recursive).
19    * The logic of the lemma is in its body (it is like FStar) - returning of () means
20    * "true/fact!", and we prove the base of the induction for an empty list then
21    * we state that for non-empty list we pass through it to the base case ("next step"?),
22    * the proposition that we prove is B, ie:
23    *
24    *   ∀x: 0 <= x < n                             (any integer that is also valid index)
25    *   list_elems_are_correct_index (l ++ [x]) n  (property is preserved after .. ++ [x])
26    * 
27    *)
28   let rec lemma list_elems_are_correct_index__append_singleton (l: L.list int) (x n: int) =
29   requires { list_elems_are_correct_index l n /\ 0 <= x < n }
30   variant { LL.length l }
31   ensures { list_elems_are_correct_index (l ++ L.Cons x L.Nil) n }
32     match l with
33     | L.Nil      -> ()
34     | L.Cons _ r -> list_elems_are_correct_index__append_singleton r x n
35     end
#+end_example

The idea of the lemma is that instead of asking the solver to discover that appending a *VALID*
singleton preserves the property while reasoning about a growing list, the program can call the
lemma and use its postcondition. Look:

#+begin_example
requires:                              
    P(r) /\ Q

ensures:
    P(r ++ [x])

  I n d u c t i o n :
    
P([])                  -- base
P(y::r) -> P(r)        -- obtain ind. hypothesis (IH)
IH                     -- recursively prove tail
--------------
P(y::r)
#+end_example

What does ~L.Nil -> ()~ mean in the lemma? It means:

#+begin_quote
1. There is no any PROGRAM operation to perform (it's ~let~ lemma)
2. Just verify that the contract follows from the current logical context (i.e., preconditions,
  postcondition)
#+end_quote

Lets simplify them:

#+begin_example
 1   predicate P (l) (n) =
 2     match l with
 3     | Nil -> true
 4     | Cons x r -> 0 <= x < n /\ P r
 5     end
 6   
 7   let rec lemma foo (l) (x) (n) =
 8     requires { P l n /\ 0 <= x < n }
 9     variant { length l }
10     ensures { P (l ++ [x]) n }
11   
12     match l with
13     | Nil -> ()
14     | Cons _ r -> foo r x n
15     end
#+end_example

** Case 1: l = []

Why3 enters ~| Nil -> ()~ - unit, so, NO RECURSIVE CALL: EXECUTE NOTHING, PRODUCE ~()~.

*But Why3 still must verify the CONTRACT (pre/postconditions)*

- Precondition ~P [] n /\ 0 <= x < n~.
- Why3 automatically unfold ~P~, knowing its definition, from that definition it found that
  when ~l~ is ~Nil~, the result is true: ~P Nil n -> true~, so now: ~true /\ 0 <= x < n~.
- So, THIS IS THE PRECONDITION (!!!).
- Postcondition is ~P (l ++ [x]) n~, currently ~l = []~, so the postcondition is ~P ([] ++ [x])
  n~. Again, Why3 must still prove: PRE -> POST.
- Why3 knows the definition of ~++~ (see the module ~Append~ in
  ~/usr/share/why3/stdlib/list.mlw~). So, the result of ~[] + some_list -> some_list~ and
  the postcondition becomes ~P [x] n~.
- To prove it Why3 again goes to ~P~ definition and unfolds ~P [x]~: it is ~0 <= x < n /\ P []~.
- ~P [] n~ is true, again. So, the postcondition is ~0 <= x < n /\ true~.
- Now Why3 HAS COMPLETELY UNFOLDED POSTCONDITION TOO. They are:
  PRE: ~true /\ 0 <= x < n~. POST: ~0 <= x < n /\ true~. Tautology, so PRE -> POST is proven!!!

Why3 always must prove PRE -> POST, but sometimes also it should execute code, sometimes - no.

** Case 2: l = [y]

Now Why3 enters ~| Cons _ r -> foo r x n~ (~foo~ here is the recursive call of the lemma).
~r = []~, cos ~l = y :: []~. Why3 walks into recursive call:

- Precondition now is ~P [y] n /\ 0 <= x < n~.
- Why3 unfold ~P [y] n~ again: ~0 <= y < n /\ P [] n~ (as we remember ~P [] n~ is true)
- and so on... Recursive structure of the verification look as:

#+begin_example
foo [a,b,c] x n
│
├── requires: P([a,b,c],n) /\ 0 ≤ x < n
│
├── recursive call: foo [b,c] x n
│   │
│   ├── requires: P([b,c],n) /\ 0 ≤ x < n
│   │
│   ├── recursive call: foo [c] x n
│   │   │
│   │   ├── requires: P([c],n) /\ 0 ≤ x < n
│   │   │
│   │   ├── recursive call: foo [] x n         ⋱  now this is proven:
│   │   │   │                                   :   P [] n /\ ≤ x < n
│   │   │   ├── requires: P([],n) /\ 0 ≤ x < n  :   -----------------
│   │   │   │                                   :   P [x] n
│   │   │   └── ensures: P([x],n)              ⋰
│   │   │
│   │   └── ensures: P([c,x],n)
│   │
│   └── ensures: P([b,c,x],n)
│
└── ensures: P([a,b,c,x],n)


and the top claim is proven:  P([a,b,c],n) /\ 0 ≤ x < n
                              -------------------------
                              P([a,b,c,x],n)
#+end_example

#+begin_quote
The ensures of the recursive call is used to prove the ensures of the enclosing invocation.
#+end_quote

* Hoare triples and difference with traditional asserts

https://en.wikipedia.org/wiki/Hoare_logic#Hoare_triple
TODO

* The difference with Rocq, LEAN - dark side

TODO about timeouts, OOM
