#+title: Why3: debug, part 1
#+description: Debug of failures in Why3
#+keywords: Why3,debug,Theorem,Proving
#+options: smartquotes:nil
#+options: html-style:nil html-scripts:nil author:nil validate:nil html-allow-html:t tex:t ':nil ...:nil -:nil
#+property: header-args :eval no-export
#+tags: Why3 Debug Theorem Proving 
#+date: <2026-10-08 Thu 21:17>

* Failure

Lets say we have such WhyML code:

#+begin_example
module Call1
  use int.Int

  type trace = { mutable f1_calls: int }

  let ghost trace : trace = { f1_calls = 0 }

  predicate f1_was_called (before after: int) = after = before + 1
  predicate f1_was_not_called (before after: int) = after = before  

  let ghost f1 () : unit
    writes { trace.f1_calls }
    ensures { f1_was_called (old trace.f1_calls) trace.f1_calls }
  =
    trace.f1_calls <- trace.f1_calls + 1

  let f2 (a1: int) : int
    writes { trace.f1_calls }
    ensures { result = if a1 = 0 then 100 else 101 }
    ensures { a1 = 0 -> f1_was_not_called (old trace.f1_calls) trace.f1_calls }
    ensures { a1 <> 0 -> f1_was_called (old trace.f1_calls) trace.f1_calls }
  = if a1 = 0 then begin
     f1 ();
     100
    end
    else begin
      f1 ();
      101
    end

  let main () : unit
    requires { trace.f1_calls = 0 }
    ensures { trace.f1_calls = 0 }
  =
    let _ = f2 0 in
    ()

end
#+end_example

it is explained [[file:Why3_Trace.org][here]]. If to prove it:

#+begin_example
$ why3 prove Call1.mlw -P z3 
File Call1.mlw:
Goal f1'vc.
Prover result is: Valid (0.00s, 38 steps).

File Call1.mlw:
Goal f2'vc.
Prover result is: Unknown (sat) (0.00s, 258 steps).

File Call1.mlw:
Goal main'vc.
Prover result is: Valid (0.00s, 40 steps).
#+end_example

i.e., ~f2~ cannot be proven. What does it mean?

* Messages

See [[https://why3.org/api/Call_provers.html][this]]:

#+name: prover_answer
#+begin_example
type prover_answer = 
| Valid                   (* The task is valid according to the prover *)
| Invalid                 (* The task is invalid *)
| Timeout                 (* The task timeouts, ie it takes more time than specified *)
| OutOfMemory             (* The task runs out of memory *)
| StepLimitExceeded       (* The task required more steps than the limit provided *)
| Unknown of string       (* The prover can't determine if the task is valid *)
| Failure of string       (* The prover reports a failure *)
| HighFailure of string   (* An error occured during the call to the prover
                             or none of the given regexps match the output of the prover *)
#+end_example

Why3 forms a request to SMT and the result of SMT is "sat":

#+begin_example
Prover result is: Unknown (sat) (0.00s, 258 steps).
                           ^^^
                         t h i s
#+end_example

There are 2 different questions a solver can ask about a Why3 /verification condition (VC)/:

- Is the formula satisfiable (sat)? Can it be true under some assignment of values?
- Is the formula unsatisfiable (unsat)? Is there no assignment of values that makes it true?

For verification, Why3 normally wants to prove that the VC is
valid. An equivalent way to do that is to ask whether its negation is
unsatisfiable.

So, possible answers of SMT in short are:

| Solver result | Meaning for verification                      |
|---------------+-----------------------------------------------|
| unsat         | No counterexample exists; the VC is proved.   |
| sat           | A counterexample exists; the VC is not valid. |
| unknown       | The solver cannot decide.                     |

Why3 translates the prover's responses into its own result categories,
including ~Valid~, ~Invalid~, and ~Unknown~ - see [[prover_answer][prover answer]].

So, the result is "The prover can't determine if the task is valid", and SMT returned "sat".

* SMT requests

We can check it watching the requests to the SMT solver. First, create
directories, let's say "A" and "B" (~mkdir A B~) and then:

#+begin_example
$ why3 prove Call1.mlw -P z3 -T Call1 -G "f2'vc" -o A
#+end_example

This command saves the request corresponding to the goal ~f2~ to SMT
in a directory ~A/~, there you can see only one file, e.g.,
~Call1-Call1-f2qtvc.smt2~.

If to execute:

#+begin_example
$ why3 prove Call1.mlw -P z3 -o B
#+end_example

There:

#+begin_example
B
├── Call1-Call1-f1qtvc.smt2
├── Call1-Call1-f2qtvc.smt2
└── Call1-Call1-mainqtvc.smt2

1 directory, 3 files
#+end_example

There are 3 requests of SMT regarding 3 goals (~f1~, ~f2~,
~main~). But we have a problem with ~f2~ only, so lets see it:

#+begin_example
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; generated by SMT-LIB strings
;;; SMT-LIB2: integer arithmetic
(declare-datatypes ((trace 0))
  (((traceqtmk (f1_calls Int)))))

;; "f1_was_called"
(define-fun f1_was_called ((before Int) (after Int)) Bool
  (= after (+ before 1)))

;; Goal "f2'vc"
;; File "Call1.mlw", line 17, characters 6-8
(assert
  (not
  (forall ((trace1 Int))
    (forall ((a1 Int))
      (ite (= a1 0)
        (forall ((trace2 Int))
          (=>
            (f1_was_called trace1 trace2)
            (and
              (= 100 (ite (= a1 0) 100 101))
              (and
                (=> (= a1 0) (= trace2 trace1))
                (=> (not (= a1 0)) (f1_was_called trace1 trace2))))))
        (forall ((trace2 Int))
          (=>
            (f1_was_called trace1 trace2)
            (and
              (= 101 (ite (= a1 0) 100 101))
              (and
                (=> (= a1 0) (= trace2 trace1))
                (=> (not (= a1 0)) (f1_was_called trace1 trace2)))))))))))

(check-sat)
#+end_example

And we can try it in SMT (currently, I use Z3):

#+begin_example
$ z3 Call1-Call1-f2qtvc.smt2 
sat
#+end_example

Bingo!

-------------------------------------------------------------


#+begin_example
$ why3 prove Call1.mlw -P z3 --debug vc_debug
#+end_example


#+begin_example
 1   <vc_debug>Calling eval_match with keep_trace = true
 2   K VAL ;
 3     LET o = 0;
 4     LET result = trace'mk o;
 5     LET trace'mk'result = result;
 6     STOP true
 7   K VAL _;
 8     LET trace = trace1;
 9     LET o1 = 1;
10     LET o2 = trace1.f1_calls;
11     LET f1_calls'result = o2;
12     LET o3 = o2 + o1;
13     LET (+)'result = o3;
14     HAVOC { trace @rho -> { f1_calls1 -> [o3]; }};
15     VAL result1;
16     STOP f1_was_called (trace.f1_calls) (trace1.f1_calls)
17   vars = (trace1 -> trace2)
18   regs = (trace @rho -> trace2)
19   <vc_debug>Calling eval_match with keep_trace = true
20   K VAL a1;
21     LET trace3 = trace1;
22     LET o4 = 0;
23     LET o5 = if a1 = o4 then True else False;
24     LET (=)'result = o5;
25     IF o5
26     THEN LET o6 = ();
27          LET trace4 = trace1;
28          HAVOC { trace @rho -> { f1_calls1 -> []; }};
29          VAL _1 WITH f1_was_called (trace4.f1_calls) (trace1.f1_calls);
30          LET f1'result = _1;
31          LET result2 = 100
32     ELSE LET o7 = ();
33          LET trace5 = trace1;
34          HAVOC { trace @rho -> { f1_calls1 -> []; }};
35          VAL _2 WITH f1_was_called (trace5.f1_calls) (trace1.f1_calls);
36          LET f1'result1 = _2;
37          LET result2 = 101;
38     STOP result2 = (if a1 = 0 then 100 else 101) &&
39          (a1 = 0 -> f1_was_not_called (trace3.f1_calls) (trace1.f1_calls)) &&
40          (not a1 = 0 -> f1_was_called (trace3.f1_calls) (trace1.f1_calls))
41   vars = (trace1 -> trace6)
42   regs = (trace @rho -> trace6)
43   vars = (trace1 -> trace7)
44   regs = (trace @rho -> trace7)
45   <vc_debug>Calling eval_match with keep_trace = true
46   K VAL _3 WITH trace1.f1_calls = 0;
47     LET o8 = 0;
48     LET trace8 = trace1;
49     HAVOC { trace @rho -> { f1_calls1 -> []; }};
50     LET _4 = if o8 = 0 then 100 else 101 WITH
51         (o8 = 0 -> f1_was_not_called (trace8.f1_calls) (trace1.f1_calls)) /\
52         (not o8 = 0 -> f1_was_called (trace8.f1_calls) (trace1.f1_calls));
53     LET f2'result = _4;
54     LET result3 = ();
55     STOP trace1.f1_calls = 0
56   vars = (trace1 -> trace9)
57   regs = (trace @rho -> trace9)
58   <vc_debug>Calling eval_match with keep_trace = true
59   File Call1.mlw:
60   Goal f2'vc.
61   Prover result is: Unknown (sat) (0.00s, 258 steps).
#+end_example

#+begin_example
$ why3 prove Call1.mlw -P z3 --print-theory
#+end_example


#+begin_example
 1   theory Call1
 2     
 3     (* use why3.BuiltIn.BuiltIn *)
 4     
 5     (* use why3.Bool.Bool *)
 6     
 7     (* use why3.Unit.Unit *)
 8     
 9     (* use int.Int *)
10     
11     type trace =
12       | Trace'mk (f1_calls:int)
13     
14     (* meta model_record function f1_calls *)
15     
16     predicate f1_was_called (before:int) (after:int) = after = (before + 1)
17     
18     predicate f1_was_not_called (before:int) (after:int) = after = before
19     
20     goal f1'vc :
21       forall trace:int.
22        let trace'unused = Trace'mk trace in
23        let trace'unused1 = Trace'mk trace in
24        let f1_calls'result'unused = trace in
25        let o = trace + 1 in
26        let (+)'result'unused = o in
27        forall trace1:int.
28         let trace'unused2 = Trace'mk trace1 in
29         trace1 = o -> f1_was_called trace trace1
30     
31     goal f2'vc :
32       forall trace:int.
33        let trace1 = Trace'mk trace in
34        forall a1:int.
35         let trace'unused = trace1 in
36         let (=)'result'unused = (if a1 = 0 then True else False) in
37         if a1 = 0
38         then let trace'unused1 = trace1 in
39              forall trace2:int.
40               let trace'unused2 = Trace'mk trace2 in
41               f1_was_called trace trace2 ->
42               (let result'unused = 100 in
43                100 = (if a1 = 0 then 100 else 101) &&
44                (a1 = 0 -> f1_was_not_called trace trace2) &&
45                (not a1 = 0 -> f1_was_called trace trace2))
46         else let trace'unused1 = trace1 in
47              forall trace2:int.
48               let trace'unused2 = Trace'mk trace2 in
49               f1_was_called trace trace2 ->
50               (let result'unused = 101 in
51                101 = (if a1 = 0 then 100 else 101) &&
52                (a1 = 0 -> f1_was_not_called trace trace2) &&
53                (not a1 = 0 -> f1_was_called trace trace2))
54     
55     goal main'vc :
56       forall trace:int.
57        let trace'unused = Trace'mk trace in
58        trace = 0 ->
59        (let trace'unused1 = Trace'mk trace in
60         forall trace1:int.
61          let trace'unused2 = Trace'mk trace1 in
62          let _'unused = (if true then 100 else 101) in
63          (true -> f1_was_not_called trace trace1) /\
64          (false -> f1_was_called trace trace1) ->
65          (let f2'result'unused = (if true then 100 else 101) in trace1 = 0))
66     
67   end
#+end_example
