#+title: Multidimensional Time
#+description: Models where time is not 1 dimension
#+keywords: multidimensionality,time
#+options: smartquotes:nil
#+options: html-style:nil html-scripts:nil author:nil validate:nil html-allow-html:t tex:t ':nil ...:nil -:nil
#+property: header-args :eval no-export
#+tags: Multidimensionality Time
#+date: <2026-08-30 Sun 14:37>

* Intro

In the article [[./Time.org][Is time a dimension?]] I tried to describe an understanding that time is not
a dimension. And in that article I promised to describe opposite option. But first let's
clarify the arguments against time as a dimension.

We looked at the situation with a car running over a cat. To survive, at least one
coordinate of the cat had to mismatch with the corresponding coordinate of the car. And if
time were a coordinate, then all the cat's spatial coordinates could coincide, except for
one - the time coordinate, and this would help the cat to escape. And such speculation
exists: it is claimed that the cat's coordinates could have been the same as those of a
car passing by the cat's house, but the cat was here, at this same point in space,
yesterday! That is, the time coordinates didn't match, and the cat is alive. This line of
reasoning can be refuted as follows:

just ask, *where is the cat now when a car passes this place on the road where it was
yesterday?* Indeed, if it was here yesterday, then today it's somewhere else, for
example, sitting next to the road and looking at a car. And it's alive: because at least
one of its coordinates - depth - doesn't match the car's. And yesterday it didn’t die not
because its time coordinate was different, but because yesterday its spatial coordinates
again didn’t coincide with the spatial coordinates of the car.

So, that was yesterday. And today the cat is somewhere again, sitting next to the road,
and *what makes you think its in a different time coordinate than the car's?!*

Yesterday, when it was saved, being in a different place again, *was cat's time coordinate
different from the car's?* Why?! Just because the cat was walking in this place on this road,
and the car was parked on the side of the road, nearby?

Physics thinks differently, it had the same time coordinates (and from the point of view
of the theory of relativity, too).

* The time is a strange "dimension"

Whether time is "really" a dimension in the same ontological sense as space is still open
to interpretation. To identify a point of an axis we need a coordinate - to find it, it is
an "address" of a point. If somewhere something happened, to identify this /event/ we need
its "coordinates". They are ~(x, y, z, t)~. This forces us to interpret time as a
coordinate.

Space dimensions allow you to move along some of them independently, without to change
your other coordinates, the time is different: changing your "x", you change always your
"t" coordinate, so phisicists came to [[https://en.wikipedia.org/wiki/Lorentz_transformation][Lorenz transformations]] and to the concept of
[[https://en.wikipedia.org/wiki/Spacetime][Spacetime]]. So, 3 space dimensions and 1 non-spatial dimension form this, "new" object -
"Spacetime continuum"...

* What if time is not 1 dimension?

The idea that time might have more than 1 dimension is a real idea in theoretical
physics - not established fact, but something that has appeared in several serious
frameworks. There are different ideas, theories of multidimensional "time" (I quoted it!),
in general, some of them talk about additional time-dimensions, treating it as multiple
yesterdays, tomorrows, and another theories just talk about non-spatial dimensions (they
can be not exact time or something else)...

Let's start from esoteric view of the multidimensional time ideas.

* Esoteric interpretation of multidimensional time

First theory is the theory of Russian esoteric [[https://en.wikipedia.org/wiki/P._D._Ouspensky][Piotr Ouspensky]] (1878) - a Russian philosopher and
esotericist known for his expositions of the early work of the Greek-Armenian teacher of
esoteric doctrine George Gurdjieff. He devoted quite a lot of attention to this issue and
described in detail what he means by "multidimensial time". Next I will briefly describe
his ideas.

** Ouspensky's multidimensial time

Ouspensky looked at the time axis:

#+begin_example
                  now
past <---- -  - ---+--- -  - ----> future
        my                   my
      birth                 death
#+end_example

and he asked himself, what if we have another dimension of the time? Then it would look
as:

#+begin_example
     _ _ _ _￪_ _ _ _
     _ _ _ _|_ _ _ _
     _ _ _ _|_ _ _ _ 
past -------+--------> future
#+end_example

ok, but what are these parallel lines? He thought that if we look at a regular axis, we
see numbers on it. On a parallel axis, we see the same numbers - the numbers make up the
axis. This is a definition from mathematics. It's key moment, lets remember it!

And he then reasoned as follows: on this axis we have time - the events of our lives are
isomorphic to it. OK, then the parralel lines? They *repeat* the same numbers... the same
events in our life. How to call the 2nd time dimension (5th dimension in such esoteric
"spacetime")? He called it /Eternity/ and... "recurrence". Yes, it is about [[https://en.wikipedia.org/wiki/Eternal_return][eternal
return]]. Here, Ouspensky made some interesting conclusion: looking at REPEATED time axis
(forming the time plane) he said - it is naturally recurrent! Time axis look as naturally
recurrent structure, like "laid cord". Look how it can be "proven": 

#+begin_example
     _ _ _ _￪_ _ _ _              who is living here?!
     _ _ _ _|_ _ _ _              and here too...?
     _ _ _ _|_ _ _ _
past -------+--------> future     you are living here!
#+end_example

So, your timeline is "obvious" - you are experiencing, living it! But others? Who are
experiencing them?! Not John (you), but some Kemal? Why??? They are parallel and *NO
DIFFERENCE BETWEEN THEM*. I think, we can suggest that John (you) are living them too,
but... when if you are here and you and the one?! We can suppose that it happens
some...where... You have one consciousness. No your duplicates (it is also very deep
philosophical problem: identity, ability to have full "copies", highly likely it is
impossible). So, Ouspensky suggested that your consciousness is here, on your
timeline. Then, some day (when? he suggested after the death), you will be able to pass
throung another, parallel timeline. The vertical time dimension is called "Eternity"
because every now goes on forever vertically. And it is called "recurrence" because
parallel timelines REPEAT EACH OTHER and the uniqueness of consciousness ensures
"repeatability" (recurrence) - but, to be honest, it is not 100% necessary (if
consciousnesses can be cloned, copied, be isolated). 

So, the a human history looks as:

#+begin_example
birth event1 event2 ... event3 event4 death, then
birth event1 event2 ... event3 event4 death, then
birth event1 event2 ... event3 event4 death, then
...again and again
#+end_example

Then Ouspensky thought, hm, OK, it looks like torture (he didn't know about the movie
"Groundhog Day", but he invented its script), what can help here? Yet another time
dimension! And now we have 3 time dimensions:

#+begin_example
           eternity
              .
   +------+  .
  /      /| . 
 +------+ |.
 |      | +
 |      |/
 +------+ · · · · · timeline
        |
        :
        :
        :
  possibilities
#+end_example

The new dimension gives totality of possibility - it forms parallel time planes, you can
make decision, to choose your destiny:

#+begin_example
         B
        /
A------o-------> C
        \
         D
#+end_example

British writer [[https://en.wikipedia.org/wiki/John_G._Bennett][J.G. Bennett]] supported these ideas.

** Criticism of the Ouspensky's model

First,

why are events the same on parallel timelines? Why are not possibilities actualized
immediately in the parallel timelines? If one timeline is ~{event1, event2, event3, ...}~
then another one could be ~{event5, event6, event7, ...}~.

Ouspensky answered it: *"The 5th dimension is repetition of the actualized."* But 5
dimensions alone do not mathematically imply recurrence. So, this position is accepted as
is - this follows from the definition of the 5th dimension introduced by him. He did it
using this his definition:

#+begin_quote
5th dimension - eternity - is the infinite existence of every moment of time.
#+end_quote

The second,

if he used this logic, then it can be used with vertical planes too, with the 6th
dimension (3rd time dimension), why not? Then we could have all 3 time dimensions as
repeating of one timeline - it is *underdetermination problem*: the geometry doesn't
uniquely determine which temporal coordinate represents recurrence and which represents
possibility, they both can represent reccurence!

There is an even deeper *symmetry problem*: suppose we rotate this 6-dimensional
coordinate system. In ordinary geometry, there's nothing intrinsically special about ~0x~
versus ~0y~, *if the geometry is /isotropic/, we can rotate our axes*.

So, I could answer:

- it is so by the definition of Ouspensky
- his system is /anisotropic/ by definition

His vision is:

- 3D = space
- 4D = time
- 5D = eternity or recurrence
- 6D = possibility

and then the "period" is complete (he said it explicitly). *Ouspensky made a specific
metaphysical choice about what the additional dimensions mean.*

** Antiquity

It's very interesting but the idea if eternal return existed in the antiquity even! First,
Pythagoras believed in such possibility. Eudemus of Rhodes repeated it, the Stoics also
tought that "...the universe is periodically destroyed in an immense conflagration
(ekpyrosis), and then experiences a rebirth (palingenesis). These cycles continue for
eternity, and *the same events are exactly repeated in every cycle.*" So, here we have
eternity again, but no wording about other dimensions of times. Does "eternity" imply the
existence of an additional dimension of time?

The answer is that many schools and philosophers thought about time and saw it as
different structures but maybe only Ouspensky did it in so geometric manner allowed us to
talk about time dimensions directly, explicitly. All others (Hindu cosmology, Yoga
Vedanta, Buddhism, Greek philosophy, Neoplatonism, Hermetic traditions, Gnosticism,
Kabbalah even, Nietzsche...) did not talk about DIMENSIONS of TIME. They used other
terminology, not geometric one.

* Scientific view of multidimensional time

Ordinary physics has 3 dimensions of space + 1 dimension of time: ~3+1~. Some theories
explore ~3+2~, ~4+2~, or even more dimensions, where more than one coordinate behaves like a
time dimension. ~nT~ notation is also used: ~1T~, ~2T~ etc.

Wikipedia:

#+begin_quote
The additional dimensions may be similar to conventional time, compactified like the
additional spatial dimensions in string theory, or components of a complex time
(sometimes referred to as kime).
#+end_quote

2T spacetime can have 2 equivalent time dimensions as well as 1 real time dimension and
one [[https://en.wikipedia.org/wiki/Imaginary_time][imaginary time dimension]] - in this case we have complex time plane (similarly to
usual, space complex plane).

Mathematically, imaginary time allows to avoid singularity:

#+begin_quote
...appears as a singularity in ordinary time but, when modelled with imaginary time, the
singularity can be removed and the Big Bang functions like any other point in
four-dimensional spacetime.
#+end_quote

Turkish theoretical physicist [[https://en.wikipedia.org/wiki/Itzhak_Bars][Itzhak Bars]] popularized the idea of 2T:

#+begin_quote
[He] has proposed models of a two-time physics, noting in 2001 that "The 2T-physics
approach in ~d + 2~ dimensions offers a highly symmetric and unified version of the
phenomena described by 1T-physics in d dimensions."
#+end_quote

Another example is Vladilen S. Barashenkov.

Vladilen S. Barashenkov was a Soviet/Russian theoretical physicist at JINR in Dubna,
working in nuclear and particle physics.

He explicitly developed a 6-dimensional Spacetime with a 3-dimensional vector of time:
\(\hat{t} = (t1,t2,t3)\) and ordinary 3-space: \( x=(x,y,z) \).

His 1999 paper was literally called [[https://journals.tubitak.gov.tr/physics/vol23/iss5/2/]["Multitime generalization of Maxwell electrodynamics
and gravity."]] he derived equations using a 6-dimensional space with a 3-dimensional
time vector.

Then in 2004 he and collaborators published [[https://www.researchgate.net/publication/242235885_QUANTUM_FIELD_THEORY_WITH_THREE-DIMENSIONAL_VECTOR_TIME]["Quantum Field Theory with Three-Dimensional
Vector Time."]] The model treats particles as moving along arbitrary trajectories in the
6-dimensional spacetime.

Also he had a popular book called "The Universe in an Electron" where he discusses
explosions, nuclear physics, cosmology, and even asks why space is 3-dimensional while
time is 1-dimensional.

His 6-dimensional metric is:

\begin{aligned}
d\hat{x}^2 = dx^2 - d\hat{t}^2 \quad \text{where} \\
d\hat{t}^2 = dt_1^2 + dt_2^2 + dt_3^2
\end{aligned}

Other Russian/Soviet literature on three-dimensional time, additionally to Barashenkov
could be:

- V. S. Barashenkov
- R. L. Bartini
- A. P. Yefremov
- N. A. Zhuk
- I. A. Urusovsky
- D. G. Pavlov
- and others.

Another scientist is E.A.B. Cole. Cole proposed treating 3 temporal coordinates ti as
independent, with proper time t acting as a parameter defining a trajectory through the
3-dimensional time space. This was already being discussed around 1980.

* In the context of the theory of relativity

In the theory of relativity every moving "coordinate system" has its own local time and a
British philosopher [[https://en.wikipedia.org/wiki/J._W._Dunne][J.W. Dunne]] suggested that, in the context of a "block" spacetime as
modelled by General Relativity, a second dimension of time was needed in order to measure
the speed of one's progress along one's own timeline. This leaded to an infinite regress,
but as we saw before, 2T systems exist.

* Problems with 2T

The second real (not imaginary) time dimension could lead to:

- negative-norm states
- instabilities
- problems defining probabilities
- causality problems
- particles with unusual energy behavior
- difficulty defining a sensible initial-value problem

It is like "nature seems to strongly prefer one time direction" if to believe that time
exists at all.

Example - "violation of causality":

#+begin_example
 t₂
  ↑
  |   C     D
  |   :   ⋰
  |   : ⋰
  |   A·····B
  +-----------→ t₁
#+end_example

If there was an event ~A~ and 2 equivalent time dimensions then after ~A~ can happen even
~B~, but also it can be something totally unexpected: ~C~ looking for t_1 as an event
happening at the same time as ~A~. Also there are possibilities of complex timelines -
like the event ~D~. But again: maybe the paradoxes of elementary particles and quantum
mechanics explained by this? Another point defending multiple equivalent time dimensions
could be the next reasoning: maybe we already live in such Mutlitime-Space but we treat
~(t1, t2, ...)~ cootdinates as one complex coordinate ~t~? Sure, such fantasy requires
strong definitions... I mean, 1T physics could emerge from 2T physics, because of special
constraints, symmetries, an observer could effectively experience: 3+1 Spacetime.

This is somewhat analogous to how a 3D object could cast a 2D shadow.

Extra time dimensions, which are (apparently) not observed in the macrocosm, are
considered compactified (folded up), similar to the extra spatial dimensions in string
theory. They exist, and they could create problems, but they are too small. A dimension
can't be small; it is infinite by definition, but given the possibility of space
curvature, such a curling up, folding is permissible.

Also multiple time directions can introduce states with problematic signs - sometimes
called ghost states. Ghost state is a state whose mathematical properties can cause the
theory to have negative probabilities or catastrophic instabilities. But again, don't we
observe them in quantum physics?

Additional time dimensions can make a lot of problems

- what determines motion in $t_1$?
- what determines motion in $t_2$?
- what is causality?
- what determines the observer's proper time?
- how does quantum mechanics work?
- how do particles propagate?
- how is energy defined?
- why don't we observe violations of causality?
- why do macroscopic systems appear to have one time direction?

* Returning time back to the dimensions

[[./Time.org][Here]] I shared my thoughts on why time is not like a dimension. Let's try to look at it as
a dimension. The problem was that kinematics equations look as:

\begin{aligned}
x(t) = \ldots \\
y(t) = \ldots \\
z(t) = \ldots
\end{aligned}

and ~t~ is a parameter (argument), not an individual dimension, just a parameter. Funny,
but at the same time we describe some event (something happened somewhere and sometime) as
\((x, y, z, t)\) and ~t~ here looks as usual coordinate... Actually, we don't need $x, y,
z$ if we know the equations of the motion, but usually we don't (and cannot) know them.

Well, to get out of this situation we can imagine:

\begin{aligned}
x(t_2) = \ldots \\
y(t_2) = \ldots \\
z(t_2) = \ldots \\
t_1(t_2) = \ldots
\end{aligned}

This primitive trick injects a time dimension $t_1$ which looks like $x, y, z$ and they
all now depend on some another time which is again a parameter ($t_2$). Mysterious. But
pay attention: now we have 2 time dimensions. What time would we measure in this case?
Maybe $t_1$. Or $t_2$. Or \(\hat{t} = (t_1, t_2)\). Some physicists introduce 3 time
dimensions, and the event's coordinates look then: \(E = (x, y, z, t_1, t_2, t_3)\). It
means that you can have a lot of New Year's Eve parties at a club in New York! What would
be the difference between them? Well... \(E1 = (x, y, z, t_1, t_2, t_3)\) and \(E2 = (x,
y, z, t_1, t_4, t_5)\) - maybe they have difference in furnishings or lighting or... it is
about /probability/, I am thinking about quantum world now... imagine that $t_2$ can have
any value in $[0, 1]$ range (let's talk about 2T) and if $t_2 = 1$ - the event is
happening now! If $t_2$ is lesser, then... so, it can be about probability as well.

** More exotic dimension

When talking about time, people always note its unidirectionality - it is like an arrow
and always follows the growth of entropy. Debunking the concept that the time is a
dimension, I said that the idea of time actually is reduced to speed. Motion and speed. My
idea was that we have space with 3 dimensions and ability to move there and time appears
only as some artificial, instrumental concept to help us to distinct body speeds.

People have the illusion that time is a river that flows constantly. You can stop moving
along the ~x~-axis, but you can't stop moving along the time axis. Let's take this metaphor
further remembering about speed.

We know about the theoretical limitation of the maximum speed of light. All other speeds
are lower. It's like moving at an angle. Imagine a person trying to swim to the shore, but
being carried away by a river current perpendicular to their movement:

#+begin_example
∵∴∵∴∵∴∵∴∵∴∵∴∵∴∵∴∵∴∵ shore
    <----           extra-"path" due time "current"  ^
    \   ↑           intended path                    |
your \  :                                            |
eff.  \◜:   ↜〜〜〜  "river current"              0x axis
"path" \:                                            |  
        ▲           you                              |
#+end_example

Now imagine that the "river current" - perpendicular force is some mysterious force
shifting you - this force is parallel to the *time dimension*. It is perpendicular to ~0x~
because it is another dimension: they all are perpendicular to each other. You spend a lot
of energy to reach your destination point and your effective, final, apparent "path" is
longer due to the "river current" - strange current always existing - it is time! I quoted
the "path" because you swime among ~0x~ - it is ~:~ trajectory and you don't move to the
left actually - you are 3D object and you cannot shift to another dimension! But you need
more energy as you would pass this longer "your eff. path". Extra-"path" also is quoted,
it is as you passed it but you did not - you just spent additional energy without to be
able to left your spatial dimensions - you are 3D, spatial body.

This force-current (or you can imagine "wind") is along ~t~-axis. What is this extra-path,
correctly to call it "shift"? It is along ~t~-axis, so you cannot see it even. You only see
that you have inertia, your speed is limited, your effective speed is a projection. And it
happens along every axis: ~0x~, ~0y~, ~0z~: because ~t~-axis is perpendicular to all axes! 

You can try to imagine the same with 2+1 spacetime: any motion in your world (the plane)
will happen under "pressure" of a mysterious wind in ~0z~ dimension.

This model makes the time dimension more close to spatial dimensions but not exactly:

- it has some constant force
- you cannot move along this dimension (/but to be honest, I think, we could reject even
  this restriction/)

So, this metaphor returns time to dimensions assuming some constant force effecting all
bodies in 3D spatial world. What could it be? Aether's wind? Some "dark energy"? Here we
are limited only by our imagination.

* 2T and Black holes

#+begin_quote
...the properties of spacetime near a singularity change even more radically and remain
poorly understood.  It is believed that their description is only possible with the
development of a quantum theory of gravity, which describes gravitational interactions at
distances on the order of the Planck length.  For an external observer, the
worldlines of particles falling into a black hole end at the gravitational radius, and all
events for them lie above the event horizon. Anything that happens to the falling observer
below the gravitational radius appears nonexistent to the external observer, since events
below the horizon are unobservable. Thus, a falling observer experiences time that does
not exist for an external observer, while time seems to stop at the event horizon.

This situation can be interpreted as follows. There are mutually perpendicular time axes,
i.e., two times: one flows for the observer above the event horizon, and the other flows
below it.  The time coordinate below the event horizon is independent of and orthogonal to
external time.

These two times have a single point of intersection on the event horizon. Thus, the
absolute future in the spatiotemporal manifold (STM) of an external observer is a moment
in time orthogonal to the original STM, and all events beyond the absolute future occur in
a time orthogonal to the time of the external observer.

-- The multidimensional time hypothesis in the context of problems of modern physics,
   Artemenko, Spaskov, 2007
#+end_quote

Singularities, quantum world are cases looking very promising in light of the theory of
multidimensional time.

* In cinema

- [[https://www.imdb.com/title/tt5453522/][Alien Code]] (multidimensional alien beings having non-linear time caught a human to
  contact with his "impossible" from their point of view consciousness)
- [[https://www.imdb.com/title/tt2543164/][Arrival]] (multidimensional alien beings arrived to Eart and try to contact with humans) 

* Time to go crazy

Multidimensional time ("time cube") created by Otis Eugene "Gene" Ray diagnosed with
schizophrenia: https://en.wikipedia.org/wiki/Time_Cube. He posits that each day actually
consists of 4 days occurring simultaneously. Ray died in March 2015.

* The most mind-bending possibility

Here's a speculative picture - not established physics, but useful for thinking. Imagine
that what we call: "the Universe evolving in time" is actually a lower-dimensional
manifestation of a more complicated structure.

Perhaps fundamental reality looks more like: $(x, y, z, t_1,t_2, ...)$ and the particular
physical conditions of our universe select one effective temporal direction.

Then "the passage of time" could be analogous to the way a lower-dimensional observer
experiences a trajectory through a higher-dimensional structure. In that picture, time as
we experience it wouldn't necessarily be fundamental. It would be an emergent feature of
the way our physical world sits inside a deeper geometry.

It could be a script for a sci-fi movie.

Multiple-time theories are speculative theoretical possibilities. That's not the same
thing as saying they're nonsense.

There are many ideas in theoretical physics that are mathematically sophisticated and
worth investigating without having experimental confirmation...

---------------

See also:

- [[https://www.gurdjieff.org/ouspensky2.htm][P. D. Ouspensky. A Biographical Outline]]
- [[https://gurdjieff.work/texts/nmotu/chap10b.html][A New Model of the Universe by P. D. Ouspensky]]
- [[https://tianmu.org/good-work-library/aquarian/fourth-way-and-ouspensky/tertium-organum-pd-ouspensky][Tertium Organum — P.D. Ouspensky]]
- [[https://www.ouspenskytoday.org/media/cl/h-Vol-VII-Recurrence-2.pdf][RECURRENCE - Dimensions, P.D. Ouspensky]]
- [[https://www.ouspenskytoday.org/media/cl/h-Vol-VII-Recurrence-5.pdf][RECURRENCE - Time enfoldment]]
- [[https://www.universalfreemasonry.org/en/library/tertium-organum/chapter-v][Tertium Organum, Chapter V, P.D. Ouspensky]]
- [[https://www.bloomingrosepress.com/parallel-existences.html][Parallel Existences]]
- [[https://www.globalgreyebooks.com/online-ebooks/p-d-ouspensky_tertium-organum_complete-text.html][Tertium Organum by P. D. Ouspensky]]
- [[https://www.globalgreyebooks.com/online-ebooks/p-d-ouspensky_in-search-of-the-miraculous_complete-text.html][In Search of the Miraculous by P. D. Ouspensky]]
- [[https://en.wikipedia.org/wiki/Eternal_return][Eternal return concept]]
- [[https://en.wikipedia.org/wiki/Eternalism_(philosophy_of_time)][Eternalism]]
- [[https://en.wikipedia.org/wiki/Multiple_time_dimensions][Multiple time dimensions]]
- [[https://www.researchgate.net/publication/2084994_Two-Time_Physics][Two time physics]]
- [[https://arxiv.org/abs/hep-th/9809034][Two-Time Physics, Itzhak Bars]]
- [[https://www.youtube.com/watch?v=hFba6A52An0][Youtube video: Two Time Physics]]
- [[https://journals.tubitak.gov.tr/physics/vol23/iss5/2/][Multitime generalization of Maxwell electrodynamics and gravity Authors: VLADILEN BARASHENKOV]]
- [[https://studyoftime.org/][The International Society for the Study of Time]]
- [[https://phys.org/news/2025-06-theory-dimensions-space-secondary-effect.html][New theory proposes time has three dimensions, with space as a secondary effect by Rod Boyce, University of Alaska Fairbanks]]
- [[https://arxiv.org/abs/2601.14134][Multidimensional arrow of time Sergey G. Rubin]]
- [[https://iopscience.iop.org/article/10.1088/0305-4470/13/11/002][On multidimensional time J Strnad]]
- [[https://www.socr.umich.edu/spacekime/][Research project: The 5D Universe of 3D Space & 2D Complex Time]]
- [[https://wp.towson.edu/5dstm/][The 5D Space-Time-Matter Consortium]]
- [[https://www.youtube.com/watch?v=kkKviAkWb4I][Youtube video: Multidimensional Time]]
- [[https://tetrahedral.blogspot.com/2011/12/privileged-character-of-31-spacetime.html][The Privileged Character of 3+1 Spacetime]]
