#+title: Is time a dimension?
#+description: Thought about time
#+keywords: time,philosophy
#+options: smartquotes:nil
#+options: html-style:nil html-scripts:nil author:nil validate:nil html-allow-html:t tex:t ':nil ...:nil -:nil
#+property: header-args :eval no-export
#+tags: time philosophy
#+date: <2026-05-02 Sat 14:00>

* School knowledge

From school we remember that time is a coordinate - =t=, the uniform motion of some point
is described by a function like ~x(t) = k*x, v(t) = k, a(t) = 0~. And we imagined 3 space
coordinates and one additional - the time, keeping in mind that we always move to the
future, and never - back, to the past.

* Dimensions

After 90s and the development of computer graphics everyone knows what "3D" means. We have
3 space dimensions. What does it mean? It is (possible) infinite set[fn:inf_space] of
distinct "places" where objects can be located. And to understand what dimensions are, you
should remember the main rule: *dimensions are independent* in the sense that a point or
some body can move along one axis (the symbolic direction of the dimension, nothing more)
without to move along others - the movement can be independent. Imagine movement of hockey
players on the rink - intensive move to left, right, movement into the distance, towards
the opponent and back: ~X~, ~Y~ coordindates are changed but the height - the third ~Z~ is
not, it is constant. Movement along one line parallel to some axis is similar - all other
coordinates don't change. What about time?

* Time dimension

We used to think about time in the same way - "idenendent time dimension". Well, movement
along time axis is not free - you can move only forward with the same speed. Is it true?

Consider a cat crossing a street. To be crushed by a car, the cat's coordinates must match
the car's coordinates:

#+begin_example
                     ^^~
  ______             :   
 /|_||_\`.__         :   
(   _  o _ _\........✸   
=`-(_)--(_)-'              
#+end_example 

Somebody could say: They may coincide, except for the time coordinate, for example, the
cat passed in this place, but 5 minutes ago - it was saved!

Well, the cat is saved only if one of its *space* coordinates did not match, else -
death. Think about independence of coordinates: the cat cannot survive without at least
one coordinate to be different comparing to the car! The cat cannot seat on this place and
to survive because ~X,Y,Z~ coordinates matched but the time - did not. Yes, the cat can
independently change one of its coordinates: either ~X~ or ~Y~, even ~Z~ (the last one
often saves cats life!), but no way to change independently ~t~ coordinate!

Time is not real dimension. And no way to save the cat without to have at least one of its
coordinates not matching the same coordinate of the car. Just no way.

If the cat is still alive, it is not because it was there, on this street, yesterday, but
because today one of it coordinates are different. The surviving is not possible without
the second, - and this is the proof that ~t~ is not independent dimension.

We can state it differently: it is not important what coordinates the cat had yesterday.
They just don't matter. They could be absolutely any. Even the same of the car today. Only
today's coordinates matter. So,

1. the cat cannot change its ~t~ coordinate - at least independently from its ~X, Y, Z~ and
  not equally to the ~t~ coordinate of the car
2. it seems the car and the cat always have the same ~t~ coordinate.

** Conclusions

If cars and cats have always the same ~t~ coordinate (and it seems other objects too) then
the time coordinate completely loses all meaning.

* Objections

We can consider 2 different causes of cat's survival:

1. Different ~t~ coordinate of the car and the cat
2. One of space coordinates did not match

So, we should not reduce 1st to 2.

Should we take this objection into account? I thin no. Otherwise, we have try to compare
yesterday's cat with today's car which is strange: why not yesterday's cat and the
yestarday's cat as well as today's cat and today's car? A difference in only one
coordinates gives survive.

#+begin_verse
cat: x_1, y_1, z_1, t_1
car: x_2, y_2, z_2, t_2
\forall t when the cat survives, all its life: x_1 \neq x_2 \lor y_1 \neq y_2 \lor z_1 \neq z_2
#+end_verse 

and no such ~t~ in the cat's life when it is not right! Considering the opposite
situation: to die the cat has to match all car's coordinates including the time. It means
to be at the same place and the same time moment. If 1. is correct then the cat could
quickly change its ~t~ coordinate after matching ~X, Y, Z~ coordinates - how it can do
it?!

Another counterargument: to survive the cat has to change at least one of its
coordinate. It means that it will not exist more on the previous place ~(x,y,z)~ and will
be at ~(x+A, y+B, z+C)~. Let's say the car did not hit the cat at the time moment
~t1~. Did it happen because the cat did not exist at the coordinate ~t1~ when the car
existed at this coordinate ~t1~? It's wrong, it existed. But this logic work perfectly
with space coordinates: if the car exists at ~(x, y, z)~ - the survived cat did not exist
at ~(x, y, z)~ literally, it exists somewhere else. When the car did not hit the cat at
~t1~ the cat exists at the ~t1~ coordinate. It is alive because it doesn not exists at
ill-fated ~(x, y, z)~ but it did not leave ~t1~ and if the time is dimension - we will
still find the cat at the sign "t1" on the line of time - where the car is too!

So, can we eliminate time?

* A programmer's view of coordinates

What is the identity? In philosophy it's very complex problem and in general it was not
solved. But in programming it is little bit simpler: for the identity of some software
object we can use address: if addresses are the same - it is the same
object. Identical. What is "address"? We can think about it as... ~X~ coordinate:

#+begin_example

o-----------------> 0x axis

 Adr0 Adr1 Adr2
+----+----+---- -
|obj1|obj2|    |
+----+----+---- -
 obj3
#+end_example 

~obj1~ and ~obj3~ are the same object because 2 objects cannot fill the same memory
cell. But ~obj2~ is different object - it has a different address/identity criteria, or
~X~ coordinate.

And here we come to another understanding of coordinates and cats and cars: coordinates
are *identity criteria* like the address for the computer memory: if all coordinates match
then it is the same object! It's like a key in a map. So, does the identity of physical
objects require the 4rd coordinate in the "identity" ~(x, y, z, t)~ tuple? Else
cats... sometimes are cars.

* Everything is about movement

How serious is the previous objection? Quite serious, it tells that ~(X, Y, Z)~ are not
enough. Maybe missing part of identity is not one coordinate of time but something else -
not one additional coordinate but more:

#+begin_example
missing-coordinate = hash(unknown-parameter-1, unknown-parameter-2, ...)
#+end_example 

Another possibility is to keep in mind - there is such categorie that cannot be understood
but we has to accept that *it is a potency to change coordinates* during different
motions.

So, these are 2 different mental visions:

1. We add to our object yet another ID (~t~, clock tick, etc)
2. We ignore it, because time ticks are behind the scene and we can focus only of potemcy
   of change coordinates - it is different and we call it "velocity" or "speed".

We always do the 2nd. Cats cannot become cars, they are always distinct: coordinates are
not static, they always can change, with different intencity - ie, speed. Times is tightly
connected with speed and vise versa, they are like the same phenomena but viewed from
different points. Ability to change your coordinates requires speed which requires
energy - another fundamental term (one of central terms in Indian philosophy). Is it
possible to understand time/speed in static, without to consider energy?

* Space and time as memory

From one point of view we can think about time as additional identity component but then
we have open question: how do changes of identity components ("coordinates") happen?! The
answer is exactly the time, so I think it's wrong to treat it as an identity component -
it is potency to change/modify them. Then we have simple scheme like in computers, memory
can be imagined as a "space" with coordinates. The physical space can be seen in the same
way: objects are "located" at some multicomponent "addresses"/"identities". The space is a
storage of cells and reminds memory. Human memory is just neuron-based snapshot of the
state of the larger memory, called "space". The physical space keeps a state. The state is
a configuration of objects, nothing more. Real memory has refresh frequency, refreshing
the state of cells, without it physical degradation processes will erase memory. Do we
have something like this in the "real" physical world? Yes, all objects consist of
elementary particles that are called sometimes "oscillators". They remind super-small
flip-flop particles, by the way, quantum physics tells us that we will never see them. So,
we can think about space and time like about a *computer memory and memory refresh
rate*. Some objects move faster, they need lesser refresh clocks to change their "address"
(space coordinates)!

* Computational model

In reality, memory is hardware:

#+begin_example
            S P A C E
             +------+
             | M    |
 address     | E  C |
   or   x,y,z| M  H |    object:
 object ---->| O  I |--> set of
identity     | R  P |   attributes
             | Y    |
             +----o-+
                  |
time/clock -------'
#+end_example 

It pushes us to the [[./simulation.org][Simulation Hypothesis]] using about our world the metaphor of
computational device, some kind of mega-computer: refresh clock is needed not only to keep
a persistent state of memory but also it is needed to change the memory, and it restricts
the highest speed of data saving - you cannot save (move) faster. Wow! Light speed!
Physics teaches us that this is the limit of movement! And it reminds the refresh clock
rate very much.

You shouldn't be confused by the three coordinates; the first two can address the
cascading inclusion of memory blocks or form a hash.

* Time as abstraction

We saw many times the usage of time ~t~ in physics and mathematics. Physics is not so
abstract as math, it deals with real things (if to foget about theoretical physics with
its black holes, etc). School physics even. And if to ask - where the time is then? No
answer: there is only one ~t~: *now*. When we can find an object 1 second ago? Or where is
it when it's ~t~ is bigger then \( t_{now} \) ?  Time looks as very imaginary concept, a
"dimension" having only one coordinate: now. How long is it now[fn:now]?

Now turns out to be a very elusive and brief moment, like a point in geometry—reality
barely has time to appear out of nowhere before it instantly disappears into the past. And
the duration of its real existence is elusive. And this understanding of time looks too
fragile, too poetic.

So fundamental concept (categorie) as time is undefinable so much.

* Philosophical theories of time

It is full of debates and it has very long history: [[https://en.wikipedia.org/wiki/Philosophy_of_space_and_time][Space and Time in Philosophy]].  And
there are a lot of theories about time but they are often groupped in 2 categories:
A-theories and B-theories. And by the way, one of them claims that time does not exist, it
is illusion (kind of). If time does not exist, then the [[https://en.wikipedia.org/wiki/Theory_of_relativity][Theory of Relativity]] mostly stops
to exist too because time (Spacetime) is key concept there - no time, no ~t~ in their
formulas, at least they need adding of other arguments, maybe instead of ~t~.

* Spacetime

In the Theory of Relativety everything is more complex even: no one "time": every atom,
elementary particles have their own "local" times, their own "ages", simultaneous events
can be non-simultaneous events in own "time system", this theory is full of paradoxes,
contradictions and has very serious problems with experimental proving (existing proofs
can be treated in different ways without resorting of the Theory of Relativety), but today
it's accepted as "true" theory, and academic science ignores all problems around it ([[https://www.youtube.com/watch?v=iQKTG5LQ05Y][GPS
expert Ron Hatch about the theory of relativety]], well it also has problems but debates
continue and "paradoxes" still look assymetrical). Another crush can come from the Theory
of Simulation: computed world needs common clock and it means there is a global common
time system.

If time is not a dimension, then it cannot be a coordinate. It's a problem: then what is
~t~ in the formulas? Obviously, it's "instrumental" argument needed for ordering of
"events". Then:

1. If the order of independent events can be different in different time systems (by the
   Theory of Relativety) then what is the sense of this ~t~?! Initially, it was introduced
   in physics just to describe differential (speed, acceleration) when we describe motion
   of a point. So, it is "tooling", "instrumental" argument needed to see changed
   coordinates as a chain of points beloning to some continuous function (so we can do
   differentiation of a function).
2. What is "event"?

* Event

Event, in general, seems to be a point on that graph of the motion's function. And the key
feature of it is its horizontal coordinate: mystical ~t~. Where do events exist? In our
memory. Because tries to find them in the reality lead to a lot of logical, philosophical
problems.

* Age

But we fill time! We are getting old! As before: everything is about motion :) We get
older not because of time magically moved us from "now" to "yesterday", but because
molecules inside our biological cells are moved al the time, and their "good
configuration" when we were young becomes "bad configuration" - DNA defects and so on. So,
infinite movement of small particles inside us leads to death. Time does not magically
affect us, time allows particles, molecules to move and to change the configuration
(state!) of our organisms. It is again the cat and the car. 


[fn:inf_space] [[https://www.youtube.com/watch?v=qUmOKiSOLbo][Zeno]] was the first who asked, how long can we divide space to smaller
parts? Is it infinite process? And Hellenic philosophers were divided to 2 groups: the
space is "pixelazed", it also consists of small indivisible "cells" and the second group
thought the space is continuous. After greatest philosopher of the mankind Zeno, other
people took his insights and declared that we cannot divide space, time, matter
infinitely: Democritus, Epicurus, Diodorus Cronus ("time consists of NOW moments"). The
father of logic - Aristotle was on the opposite side.
[fn:now] Indian philosophers also were divided to 2 camps and one of the camps stood on
the idea of discrete reality: in [[https://en.wikipedia.org/wiki/Bhagavata_Purana][Bhagavata Purana]] the smallest unit of matter is called
~paramanu~ (it is the same as the atom in Ancient Greece) and also they used a smallest
unit for time - ~truti~ which is about ~1/33,750~ second (about 30 microseconds). Modern
physics has a concept of Planck time: \( t_P \approx 5.39 \times 10^{-44} \ \text{seconds} \).
It does not mean that the time is discrete (ticks), it is the smallest time that makes
sense from the point of view of phisics, under it any effects and events cannot be
differentiated by the science. Well, kind of quantum, but "pixelization" of the reality is
not proven yet (and maybe won't be).
